on:
  push:
    tags:
      - '*'
      - '*/*'
name: Release
jobs:
  release:
    name: Release GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 3
      - name: Check package version
        uses: technote-space/ga-package-version-checker@test/v0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_TAG_PREFIX: test/
      - name: Release GitHub Actions
        uses: technote-space/release-github-actions@test/v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_NAME: Technote
          COMMIT_EMAIL: technote.space@gmail.com
          OUTPUT_BUILD_INFO_FILENAME: build.json
          TEST_TAG_PREFIX: test/
          ORIGINAL_TAG_PREFIX: original/
